
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Upload, AlertCircle, CheckCircle } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';

function UploadModelDialog({ open, onOpenChange, onSubmit }) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [files, setFiles] = useState({ glb: null, usdz: null });
  const [validation, setValidation] = useState({ glb: null, usdz: null });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  const validateFile = (type, file) => {
    const maxSize = 50 * 1024 * 1024; // 50MB
    if (file && file.size > maxSize) {
      return { valid: false, message: 'File exceeds 50MB limit' };
    }
    // Simple extension check
    if (type === 'glb' && !file.name.toLowerCase().endsWith('.glb')) {
         return { valid: false, message: 'Must be a .glb file' };
    }
    if (type === 'usdz' && !file.name.toLowerCase().endsWith('.usdz')) {
         return { valid: false, message: 'Must be a .usdz file' };
    }

    return { valid: true, message: 'Valid file' };
  };

  const handleFileChange = (type, e) => {
    const file = e.target.files[0];
    if (file) {
      const result = validateFile(type, file);
      setValidation(prev => ({ ...prev, [type]: result }));
      setFiles(prev => ({ ...prev, [type]: file }));
      
      if (!result.valid) {
        toast({
          title: "Validation Error",
          description: result.message,
          variant: "destructive",
        });
      }
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!files.glb) {
        toast({ title: "Missing File", description: "GLB file is required", variant: "destructive" });
        return;
    }
    if (validation.glb?.valid === false || validation.usdz?.valid === false) return;

    setIsSubmitting(true);
    
    // Pass raw files to parent to handle upload logic
    const modelData = {
      name,
      description,
      // URLs will be generated by parent
    };

    try {
        await onSubmit(modelData, files);
        setName('');
        setDescription('');
        setFiles({ glb: null, usdz: null });
        setValidation({ glb: null, usdz: null });
    } finally {
        setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-[#151B23] border-[#29B6F6]/20 text-white sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-white">
            <Upload className="h-5 w-5 text-[#29B6F6]" />
            Upload 3D Model
          </DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Model Name *
            </label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full bg-[#0B0F14] border border-[#29B6F6]/20 rounded px-3 py-2 text-white placeholder-gray-500 focus:outline-none focus:border-[#29B6F6] transition-colors"
              placeholder="e.g., Modern Sofa"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Description
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full bg-[#0B0F14] border border-[#29B6F6]/20 rounded px-3 py-2 text-white placeholder-gray-500 focus:outline-none focus:border-[#29B6F6] transition-colors resize-none"
              placeholder="Model description"
              rows={2}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              GLB File (Android/Web) *
            </label>
            <div className="relative">
              <input
                type="file"
                accept=".glb"
                onChange={(e) => handleFileChange('glb', e)}
                className="w-full bg-[#0B0F14] border border-[#29B6F6]/20 rounded px-3 py-2 text-white file:mr-4 file:py-1 file:px-3 file:rounded file:border-0 file:text-sm file:bg-[#29B6F6] file:text-[#0B0F14] hover:file:bg-[#29B6F6]/90 file:cursor-pointer"
              />
              {validation.glb && (
                <div className="absolute right-2 top-1/2 -translate-y-1/2">
                  {validation.glb.valid ? (
                    <CheckCircle className="h-5 w-5 text-green-500" />
                  ) : (
                    <AlertCircle className="h-5 w-5 text-red-500" />
                  )}
                </div>
              )}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              USDZ File (iOS)
            </label>
            <div className="relative">
              <input
                type="file"
                accept=".usdz"
                onChange={(e) => handleFileChange('usdz', e)}
                className="w-full bg-[#0B0F14] border border-[#29B6F6]/20 rounded px-3 py-2 text-white file:mr-4 file:py-1 file:px-3 file:rounded file:border-0 file:text-sm file:bg-[#29B6F6] file:text-[#0B0F14] hover:file:bg-[#29B6F6]/90 file:cursor-pointer"
              />
              {validation.usdz && (
                <div className="absolute right-2 top-1/2 -translate-y-1/2">
                  {validation.usdz.valid ? (
                    <CheckCircle className="h-5 w-5 text-green-500" />
                  ) : (
                    <AlertCircle className="h-5 w-5 text-red-500" />
                  )}
                </div>
              )}
            </div>
            <p className="text-xs text-gray-500 mt-1">Optional, but required for AR on iPhone</p>
          </div>

          <div className="flex gap-3 justify-end">
            <Button
              type="button"
              onClick={() => onOpenChange(false)}
              variant="outline"
              disabled={isSubmitting}
              className="border-[#29B6F6]/20 text-gray-300 hover:bg-[#29B6F6]/10"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting}
              className="bg-[#29B6F6] hover:bg-[#29B6F6]/90 text-[#0B0F14]"
            >
              {isSubmitting ? 'Uploading...' : 'Upload Model'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}

export default UploadModelDialog;
